#                    _ _ 
#                   | (_)     Website: https://madi11305.github.io
#  _ __ ___ __  ____| |_      GitHub: https://github.com/madi11305
# | '_ ` _ \\ \/ / _` | |     Email: <madi11305@protonmail.com>
# | | | | | |>  < (_| | |
# |_| |_| |_/_/\_\____|_|
# .xinitrc

# Transparent Windows
picom --config ~/.config/picom/picom.conf &

# Draw Wallpaper
~/.fehbg

# slstatus
slstatus &

# Dynamic Window Manager [DWM]
exec dwm
